# 이름
name: Github Actions 연습하기

# 언제 실행할지
on:
  pull_request:
    branches:
      - main

# 할 일
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 불러오기
        uses: actions/checkout@v5

      - name: Node.js 설치하기
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: 의존성 설치
        run: npm install

      - name: 테스트실행
        run: echo "npm run test 대체"
